### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by rainbow-train** [ghe-learn/check-qmd-render-test#6]
Does @larnsce receive a notification after tagging?

**Comment by larnsce** [comment]
Yes, @rainbow-train

**Comment by rainbow-train** [comment]
But, I did not receive a notification.

**Comment by rainbow-train** [comment]
I have changed my notification settings @larnsce. Please try again.

**Comment by larnsce** [comment]
And now @rainbow-train

**Comment by larnsce** [comment]
Once again @rainbow-train

**Comment by larnsce** [comment]
Again... @rainbow-train

**Comment by rainbow-train** [comment]
Yes, it finally worked.

Under Settings -> Notifications, select that notifications are also received on GitHub. Otherwise only email.

<img width="977" alt="Screenshot 2023-10-27 at 12 36 00" src="https://github.com/ghe-learn/check-qmd-render-test/assets/78352807/1d262f7f-d4f4-4578-b66f-2282c0b20cd3">
